### ISSUE TITLE
Record five-minute screencast explaining how to use the system

### ISSUE THREAD

**Issue by RobertLRead** [CivicActions/agile-california#107]
2-3 minutes. Include video of me opening the app on my iPhone. Then cut to screencast showing demo.

**Comment by jenharris** [comment]
I will record a screencast from user perspective tomorrow (Tuesday).

**Comment by jenharris** [comment]
add website to home screen link: http://www.howtogeek.com/196087/how-to-add-websites-to-the-home-screen-on-any-smartphone-or-tablet/

**Comment by jenharris** [comment]
how to capture and record an iphone screen video: http://www.apptamin.com/blog/capture-iphone-ipad-screen-video/
