### ISSUE TITLE
Messaging "From" field blank

### ISSUE THREAD

**Issue by stevecurtis** [CivicActions/agile-california#115]

**Comment by stevecurtis** [comment]
When logged in as case-worker, viewing a message from foster-parent, "from" field is blank. Observed in Safari and Chrome. See screenshot.

**Comment by stevecurtis** [comment]
![screen shot 2016-06-05 at 9 58 08 pm](https://cloud.githubusercontent.com/assets/6162970/15833293/17275384-2bf4-11e6-93b8-dc1aecf29747.png)

**Comment by jenharris** [comment]
this has been resolved.
