### ISSUE TITLE
Errant asterisks

### ISSUE THREAD

**Issue by stevecurtis** [CivicActions/agile-california#116]

**Comment by stevecurtis** [comment]
A few places in where asterisks appear next to input fields for apparently no reason (next to "urgent" in message creation view, "I work with a foster agency", preferred child age)

**Comment by jenharris** [comment]
asterisk is no longer appearing next to "urgent"

**Comment by jenharris** [comment]
asterisk no longer appearing next to "I work with a foster agency" or "preferred child age"
