### ISSUE TITLE
API research and learnings in Github

### ISSUE THREAD

**Issue by stevecurtis** [CivicActions/agile-california#12]

**Comment by aravenrose** [comment]
API located at https://dev.socrata.com/foundry/chhs.data.ca.gov/mffa-c6z5

All communication with the API is done through HTTPS, and returns JSON, XML, and CSV. We can either query directly via the frontend using Javascript, or use the php library https://github.com/socrata/soda-php if we need backend processing.

We will have a better idea of frontend vs backend after user interviews and we know what the end users will ultimately need.
