### ISSUE TITLE
Create Evaluation Checklist for Support (Ticketing/Messaging) Systems

### ISSUE THREAD

**Issue by jmheaster** [CivicActions/agile-california#22]
We need to have a set list of features that we evaluate when considering ticketing/messaging systems.

**Comment by hrod** [comment]
https://docs.google.com/spreadsheets/d/1gtYPEd1tij22Wl5S8MpbIgUrqb0aPCdGyvi4y8aYzaU/edit Here's my first attempt at coming up with a spreadsheet. If we could have @jenharris or @aravenrose take a look at it and make edits, that would be great!

**Comment by jenharris** [comment]
Thanks, Heather - I will review!

On Fri, May 20, 2016 at 4:43 PM, Heather Rodriguez <notifications@github.com

> wrote:
> 
> Assigned #22 https://github.com/CivicActions/agile-california/issues/22
> to @jenharris https://github.com/jenharris.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/CivicActions/agile-california/issues/22#event-667704291

## 

Jen Harris
User Experience Designer
*CivicActions | *civicactions.com
347.987.0458

**Comment by jenharris** [comment]
@hrod @aravenrose Closing this ticket - the evaluation criteria looks comprehensive.
