### ISSUE TITLE
As a newbie to github I need Github Training so that I'm using the tool appropriately

### ISSUE THREAD

**Issue by jmheaster** [CivicActions/agile-california#24]
Adam to help Jen, Jason and others get antiquated with Github

**Comment by RobertLRead** [comment]
@nerdstein @jmheaster @jenharris Team, I have moved this back into the backlog.  I understand it is important, but I don't think of it as a "user story".  I'll put a "training" label on it, but I would like to get it closed --- is this something we can get done quickly?  My understanding is that Adam is an expert.

**Comment by nerdstein** [comment]
My schedule looks the most promising on this coming Monday (timezones). I've seen great progress made by the team organically. It may make sense to do a Q&A session to fill in remaining gaps. Thoughts on this approach?
