### ISSUE TITLE
As a UX'er I need to Schedule users to interview in order to obtain the user feedback

### ISSUE THREAD

**Issue by jmheaster** [CivicActions/agile-california#27]

**Comment by hpoole** [comment]
I will take scheduling end user interviews for Friday 5/27 (Henry) at 10am Pacific.

**Comment by RobertLRead** [comment]
Jason, in order to make this testable we need to put a specific date on it --- or is it already done?  I don't having a story that is open ended.

**Comment by elizabethraley** [comment]
Duplicate of #16
