### ISSUE TITLE
As a foster parent, I want to Indicate the priority / urgency of the message so that the case worker can prioritize their responses

### ISSUE THREAD

**Issue by grugnog** [CivicActions/agile-california#32]

**Comment by grugnog** [comment]
If something is urgent, it shows up in RED at the top of my inbox (MVP)

**Comment by aravenrose** [comment]
Moving Owen's comment to it's own "theme" card, and reducing estimate for message priority only.

**Comment by jenharris** [comment]
![urgent-message](https://cloud.githubusercontent.com/assets/7294004/15762600/4ba440c6-28e4-11e6-943b-b527774aa97e.png)
