### ISSUE TITLE
As a developer, I want to see wireframes representing key functionality that I need to build.

### ISSUE THREAD

**Issue by hrod** [CivicActions/agile-california#38]

**Comment by jenharris** [comment]
Trello board with personas & sketches/ideas: https://trello.com/b/oVTk68tz/agile-ca-personas-and-sketches

**Comment by hrod** [comment]
<img width="322" alt="screen shot 2016-05-24 at 11 39 23 am" src="https://cloud.githubusercontent.com/assets/4369591/15515921/3cccc9a6-21a5-11e6-956b-6b14ba4a8cb2.png">

**Comment by hrod** [comment]
Message: 
<img width="340" alt="screen shot 2016-05-24 at 12 00 19 pm" src="https://cloud.githubusercontent.com/assets/4369591/15516353/431acf54-21a7-11e6-9380-4c8e842b0a01.png">

**Comment by hrod** [comment]
![agile ca create message](https://cloud.githubusercontent.com/assets/4369591/15517176/417e770a-21ab-11e6-9419-8b662fb60ec3.png)

**Comment by hrod** [comment]
![inbox-mobile](https://cloud.githubusercontent.com/assets/4369591/15557796/39acfd0a-228a-11e6-971a-8ca1f3e6b663.png)

**Comment by hrod** [comment]
![message-mobile](https://cloud.githubusercontent.com/assets/4369591/15558158/d61f74e0-228c-11e6-8864-5df96888fd84.png)

**Comment by hrod** [comment]
![inbox-mobile](https://cloud.githubusercontent.com/assets/4369591/15583276/0d9de1e8-232a-11e6-850f-3379b11f5216.png)
![message-create-mobile](https://cloud.githubusercontent.com/assets/4369591/15583277/0db3286e-232a-11e6-82bd-5d2ed9e8fc1c.png)
![message-mobile](https://cloud.githubusercontent.com/assets/4369591/15583279/0dbc552e-232a-11e6-8f34-91dbadd6b366.png)

**Comment by jenharris** [comment]
Still to do: Desktop wireframes from the three mobile views attached

**Comment by jenharris** [comment]
Updated Create Message - Mobile wireframe: https://civicactions.mybalsamiq.com/projects/fccmodernization/Agile%20CA%20Create%20Message%20-%20Mobile

**Comment by jenharris** [comment]
Updated Create Message - Mobile wireframe: https://civicactions.mybalsamiq.com/projects/fccmodernization/prototype/Agile%20CA%20Create%20Message%20-%20Mobile?key=4c845834397d877e3a436df76d0fb114c22863b8

**Comment by jenharris** [comment]
@hrod I started working on a desktop sketch / concept here: https://civicactions.mybalsamiq.com/projects/fccmodernization/Agile%20CA%20inbox%20-%20Desktop

**Comment by jenharris** [comment]
@hrod I'm going to close this one. We can open additional tickets for more specific wireframing needs.
