### ISSUE TITLE
As a developer and UX designer, I want to see an empathy map and persona for a caseworker so I can understand their needs as it pertains to the system.

### ISSUE THREAD

**Issue by hrod** [CivicActions/agile-california#45]

**Comment by jenharris** [comment]
@hrod , I started a persona for case worker yesterday but didn't get too far (another interview will help!): https://trello.com/c/WVhKeDPB/10-rani-county-caseworker

**Comment by jenharris** [comment]
@hrod I'll take this ticket off your plate.
