### ISSUE TITLE
As a foster parent, I want to have a profile with some basic information to inform my caseworker.

### ISSUE THREAD

**Issue by RobertLRead** [CivicActions/agile-california#46]

**Comment by hrod** [comment]
Recommendations for theming: 
<img width="491" alt="screen shot 2016-06-02 at 11 02 15 am" src="https://cloud.githubusercontent.com/assets/4369591/15755450/b6c7cb08-28b1-11e6-98d4-523d047102d2.png">
Note that I don't really like the Fostering information tab; would be nicer if we could just put that as part of "Edit profile".
<img width="630" alt="screen shot 2016-06-02 at 11 15 09 am" src="https://cloud.githubusercontent.com/assets/4369591/15755817/4ed87644-28b3-11e6-8ece-f601e81bba15.png">

Would also like to move every fielded info above the bio, but was difficult to do with the source editor :)

**Comment by jenharris** [comment]
@hrod Thanks for this - I have been thinking the same thing and am now working on this at https://civicactions.mybalsamiq.com/projects/fccmodernization/Agile%20CA%20My%20account%20-%20Mobile

I am faster in myBalsamiq than any other tool, so I'm pasting screenshots of what exists in there and then remodeling.

**Comment by grugnog** [comment]
@hrod case workers have a profile also, which is why we have the profiles separated out like this - I don't think there is a simple way to include the foster parent fields on the main account settings form without them also showing up for case workers (which seems like it would be more confusing).

**Comment by jenharris** [comment]
@hrod @grugnog I think help text will help with this.

**Comment by jenharris** [comment]
Updated mobile wireframe for account/profile:

![screenshot-civicactions mybalsamiq com 2016-06-02 13-59-50](https://cloud.githubusercontent.com/assets/7294004/15757277/7052693a-28ca-11e6-825d-d3df39f2f2b7.png)

**Comment by jenharris** [comment]
Updated mobile wireframe for Edit profile tab

![screenshot-civicactions mybalsamiq com 2016-06-02 15-56-35](https://cloud.githubusercontent.com/assets/7294004/15760832/bb80cd88-28da-11e6-8f5f-87e4eaa18151.png)

**Comment by jenharris** [comment]
Updated mobile wireframe for Account Settings tab

![screenshot-civicactions mybalsamiq com 2016-06-02 15-58-32](https://cloud.githubusercontent.com/assets/7294004/15760877/ea738fae-28da-11e6-9a16-160df748b64c.png)

**Comment by jenharris** [comment]
Updated mobile wireframe for Fostering Info tab

![screenshot-civicactions mybalsamiq com 2016-06-02 16-13-05](https://cloud.githubusercontent.com/assets/7294004/15761296/034c0586-28dd-11e6-9a0a-19287ad8d88e.png)
