### ISSUE TITLE
As a foster parent, I want a wireframe for a profile with fields to contain information that case workers may find helpful.

### ISSUE THREAD

**Issue by hrod** [CivicActions/agile-california#47]
To do: Profile wireframes

**Comment by hrod** [comment]
![inbox-mobile](https://cloud.githubusercontent.com/assets/4369591/15557796/39acfd0a-228a-11e6-971a-8ca1f3e6b663.png)

**Comment by hrod** [comment]
![message-mobile](https://cloud.githubusercontent.com/assets/4369591/15558158/d61f74e0-228c-11e6-8864-5df96888fd84.png)

**Comment by hrod** [comment]
![message-create-mobile](https://cloud.githubusercontent.com/assets/4369591/15559082/0b3be2f6-2294-11e6-93c6-f55867ca6f6b.png)

**Comment by jenharris** [comment]
Draft wireframe: Foster Parent Edit Profile Mobile https://civicactions.mybalsamiq.com/projects/fccmodernization/Agile%20CA%20Foster%20Parent%20Edit%20Profile%20-%20Mobile

**Comment by jenharris** [comment]
Draft wireframe: Profile Views - Mobile https://civicactions.mybalsamiq.com/projects/fccmodernization/Agile%20CA%20Profile%20Views%20-%20Mobile

**Comment by jenharris** [comment]
I have since updated profile/account wireframes. See https://civicactions.mybalsamiq.com/projects/fccmodernization/Agile%20CA%20My%20account%20-%20Mobile

Tabs are clickable - Edit Profile, Fostering Info, Account Settings
