### ISSUE TITLE
As a caseworker, I want my families' Profile to reflect number of foster children and number of biological children in their home, so that I understand the domestic environment for the child I'm supervising

### ISSUE THREAD

**Issue by RobertLRead** [CivicActions/agile-california#65]

**Comment by jenharris** [comment]
Updated mobile wireframe, showing bio children fields on Fostering Info tab: 

![bio-children](https://cloud.githubusercontent.com/assets/7294004/15761783/b18c7598-28df-11e6-8fc7-dd7258263c83.png)

**Comment by jenharris** [comment]
Updated mobile wireframe, showing "Household status" on profile:

![household-status](https://cloud.githubusercontent.com/assets/7294004/15761936/9eccaf3a-28e0-11e6-8c10-92fc24370ac2.png)
