### ISSUE TITLE
Take out "format" and "source" but leave HTML tools

### ISSUE THREAD

**Issue by RobertLRead** [CivicActions/agile-california#66]

**Comment by hrod** [comment]
QAing this now.

**Comment by hrod** [comment]
If the acceptance criteria is to leave some basic formatting tools (i.e. bold, italic, bulleted list), the work fails. If we are OK with no formatting it passes. @grugnog

**Comment by hrod** [comment]
OH I see-- this applies to inbox only. No formatting tools are on the profile fields. That's OK.
