### ISSUE TITLE
As a case worker, I want to be able to view the time of day that the Foster parents with whom I work are available for contact, so that I can better communicate with them

### ISSUE THREAD

**Issue by RobertLRead** [CivicActions/agile-california#74]

**Comment by jenharris** [comment]
![preferred-contact-hours](https://cloud.githubusercontent.com/assets/7294004/15762243/4c538b0a-28e2-11e6-8cc7-c5e3dc94af16.png)

**Comment by jenharris** [comment]
![preferred-contact-hours2](https://cloud.githubusercontent.com/assets/7294004/15762287/8b950c12-28e2-11e6-99d6-9ddf63ece776.png)

**Comment by jenharris** [comment]
The foster parent user is able to add this info to their profile. As the prototype currently stands, the case-worker can't view it, but I assume that she would be able to as soon as the data structure were finalized. Passing this ticket.
