### ISSUE TITLE
As a site user, I want to see the logo and header for the system.

### ISSUE THREAD

**Issue by hrod** [CivicActions/agile-california#95]
CHHS Foster Hub

**Comment by hrod** [comment]
![logo](https://cloud.githubusercontent.com/assets/4369591/15842311/b10563ca-2c0c-11e6-9fa6-e8e3af6c3a17.jpg)

**Comment by hrod** [comment]
[favicon.ico.zip](https://github.com/CivicActions/agile-california/files/301615/favicon.ico.zip)
Zipping because .ico files are unsupported

**Comment by jenharris** [comment]
The logo and favicon are displaying for me in browser (tested Chrome and Firefox).
