### ISSUE TITLE
Fix map display/scroll issues

### ISSUE THREAD

**Issue by grugnog** [CivicActions/agile-california#96]

**Comment by jenharris** [comment]
@grugnog When I try to view the facilities map, I see "Showing facilities near 01010: No facilities found near 01010" (and I don't see a map at all) - I assume this is because I am not in California but want to alert you in case this is a bug. My zip code is 52245 (not 01010)

**Comment by jenharris** [comment]
This passes now - the link to "update zip" is great. I was able to use that link to change my zip code and upon saving it I was immediately brought back to the map, which loaded just fine with the new zip code.
